---
- name: Find if SQuirreL previously downloaded
  stat: path={{temp_install_dir}}/{{filename}}
  register: squirrelsql_check
  
- name: Download SQuirreL
  get_url: url={{url}} dest={{temp_install_path}}/{{filename}}
  when: squirrelsql_check.stat.exists == False

- name: Unarchive SQuirreL
  unarchive: src={{temp_install_path}}/{{filename}} dest={{temp_install_path}} copy=no
  
- name: Clean up any SQuirreL
  file: state=absent path={{install_dir}}

- name: Move directory
  command: "mv {{temp_install_path}}/{{temp_install_dir}} {{install_dir}}"  

- name: Fix ownership
  file: state=directory path={{install_dir}} owner=root group=root recurse=yes

- name: Make the Shell Script that invokes SQuirrel have execute permissions
  file: path={{install_dir}}/{{executable}} owner=root group=root mode=o+wrx

- name: Create shell script content to /usr/bin
  shell: printf '#!/bin/bash\n{{install_dir}}/{{executable}}' > /usr/bin/{{executable}}
  args:
    executable: /bin/bash
  
- name: Create desktop link for SQuirreL
  copy: src=/home/vagrant/share/files/{{app}}/{{app}}.desktop dest=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant

- name: Permissions for desktop link for SQuirreL
  file: path=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant mode="u+x,g+x,o+x"