app: jmeter
version: 3.1
url: http://mirror.its.dal.ca/apache/jmeter/binaries/apache-jmeter-3.1.tgz
filename: apache-jmeter-3.1.tgz
temp_install_path: /usr/local/src
temp_install_dir: apache-jmeter-3.1
install_dir: /opt/jmeter
executable_dir: /opt/jmeter/bin
executable: jmeter