---
- name: Find if Node previously downloaded
  stat: path={{temp_install_path}}/{{filename}}
  register: node_check
  
- name: Download Node
  get_url: url={{url}} dest={{temp_install_path}}
  when: node_check.stat.exists == False
  
- name: Unarchive
  unarchive: src={{temp_install_path}}/{{filename}} dest={{temp_install_path}} copy=no

- name: Clean up any Node
  file: state=absent path={{install_dir}}

- name: Move directory
  command: "mv {{temp_install_path}}/{{temp_install_dir}} {{install_dir}}"  
  
- name: Setup Node and NPM in Path Env variable
  lineinfile: >
    dest=/etc/environment
    state=present
    backrefs=yes
    regexp='PATH=(["]*)((?!.*?{{path_dir}}).*?)(["]*)$'
    line="PATH=\1\2:{{path_dir}}\3"