---
- name: Find if JMeter previously downloaded
  stat: path={{temp_install_path}}/{{filename}}
  register: jmeter_check
  
- name: Download JMeter
  get_url: url={{url}} dest={{temp_install_path}}/{{filename}}
  when: jmeter_check.stat.exists == False

- name: Unarchive JMeter
  unarchive: src={{temp_install_path}}/{{filename}} dest={{temp_install_path}} copy=no

- name: Clean up any JMeter
  file: state=absent path={{install_dir}}

- name: Move directory
  command: "mv {{temp_install_path}}/{{temp_install_dir}} {{install_dir}}"  

- name: Fix ownership
  file: state=directory path={{install_dir}} owner=root group=root recurse=yes

- name: Create symbolic link add to /usr/bin
  file: src={{executable_dir}}/{{executable}} dest=/usr/bin/{{executable}} owner=root group=root state=link

- name: Create desktop link for JMeter
  copy: src=/home/vagrant/share/files/{{app}}/{{app}}.desktop dest=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant

- name: Permissions for desktop link for JMeter
  file: path=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant mode="u+x,g+x,o+x"