---
- name: Find if Sublime previously downloaded
  stat: path={{temp_install_dir}}/{{filename}}
  register: sublime_check
  
- name: Download Sublime
  get_url: url={{url}} dest={{temp_install_path}}/{{filename}}
  when: sublime_check.stat.exists == False

- name: Unarchive Sublime
  unarchive: src={{temp_install_path}}/{{filename}} dest={{temp_install_path}} copy=no

- name: Clean up any Sublime
  file: state=absent path={{install_dir}}
  
- name: Move directory
  command: "mv {{temp_install_path}}/{{temp_install_dir}} {{install_dir}}"  

- name: Create symbolic link add to /usr/bin
  file: src={{install_dir}}/{{executable}} dest=/usr/bin/{{app}} owner=root group=root state=link

- name: Create desktop link for Sublime
  copy: src=/home/vagrant/share/files/{{app}}/{{app}}.desktop dest=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant

- name: Permissions for desktop link for Sublime
  file: path=/home/vagrant/Desktop/{{app}}.desktop owner=vagrant group=vagrant mode="u+x,g+x,o+x"